'use client';
import { useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { useAuth } from '@/context/AuthContext';
import styles from './page.module.css';

export default function Home() {
  const { user, loading } = useAuth();
  const router = useRouter();

  useEffect(() => {
    if (!loading && user) {
      const routes = { student: '/dashboard/student', teacher: '/dashboard/teacher', admin: '/dashboard/admin' };
      router.push(routes[user.role] || '/dashboard/student');
    }
  }, [user, loading, router]);

  return (
    <div className={styles.landing}>
      {/* Animated background */}
      <div className={styles.bgOrbs}>
        <div className={styles.orb1}></div>
        <div className={styles.orb2}></div>
        <div className={styles.orb3}></div>
      </div>

      {/* Navbar */}
      <nav className={styles.nav}>
        <div className={styles.logo}>
          <span className={styles.logoIcon}>🎓</span>
          <span className={styles.logoText}>VITAP <span className={styles.logoAccent}>LearnHub</span></span>
        </div>
        <div className={styles.navLinks}>
          <button onClick={() => router.push('/login')} className="btn btn-secondary">Log In</button>
          <button onClick={() => router.push('/signup')} className="btn btn-primary">Sign Up</button>
        </div>
      </nav>

      {/* Hero */}
      <section className={styles.hero}>
        <div className={styles.heroContent}>
          <div className={styles.heroBadge}>🚀 AI-Powered Learning Platform</div>
          <h1 className={styles.heroTitle}>
            Learn Smarter, <br />
            <span className={styles.gradient}>Not Harder</span>
          </h1>
          <p className={styles.heroDesc}>
            VITAP LearnHub is your all-in-one gamified learning management system.
            AI-generated quizzes, real-time study groups, progress tracking, and more — built for VITAP students.
          </p>
          <div className={styles.heroCta}>
            <button onClick={() => router.push('/signup')} className="btn btn-primary btn-lg">
              Get Started Free →
            </button>
            <button onClick={() => router.push('/login')} className="btn btn-secondary btn-lg">
              I have an account
            </button>
          </div>
        </div>

        {/* Feature highlights */}
        <div className={styles.features}>
          {[
            { icon: '🤖', title: 'AI Quizzes', desc: 'Unique questions generated by Gemini AI for every student' },
            { icon: '🏆', title: 'Gamification', desc: 'Earn XP, maintain streaks, unlock achievements, climb leaderboards' },
            { icon: '💬', title: 'Study Groups', desc: 'Real-time chat with classmates, share notes, learn together' },
            { icon: '📊', title: 'Analytics', desc: 'Track your growth with detailed performance insights' },
            { icon: '👨‍🏫', title: 'Multi-Teacher', desc: 'Choose your preferred teacher for each course' },
            { icon: '📄', title: 'Past Papers', desc: 'Access previous year question papers organized by exam type' },
          ].map((f, i) => (
            <div key={i} className={`card card-hover ${styles.featureCard}`} style={{ animationDelay: `${i * 0.1}s` }}>
              <div className={styles.featureIcon}>{f.icon}</div>
              <h3 className={styles.featureTitle}>{f.title}</h3>
              <p className={styles.featureDesc}>{f.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Footer */}
      <footer className={styles.footer}>
        <p>© 2024 VITAP LearnHub. Built for VITAP University.</p>
      </footer>
    </div>
  );
}
